# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/src/service/src/features/app_config/mod.rs

[prosody]
default_storage = "sql"
storage = { roster = "sql" }
sql = { driver = "SQLite3", database = "prosody.sqlite" }
sqlite_tune = "normal"

[prosody_ext]
additional_modules_enabled = ["storage_sql"]

[branding]
company_name = "Prose (benchmark)"

[notifiers.email]
smtp_host = "mailpit"
smtp_encrypt = false

[debug_only]
insecure_password_on_auto_accept_invitation = true
