[package]
name = "migration"
version = { workspace = true }
edition = { workspace = true }
publish = false
license = { workspace = true }

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { workspace = true }
sea-orm-migration = { workspace = true }
