#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)/.."}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

test-env-vars 'tutorials/run-locally.md' \
	PROSE_POD_SERVER_DIR \
	PROSE_POD_API_DIR \
	PROSE_POD_SYSTEM_DIR

# Build the Prose Pod API image.
edo task build-image -- --debug

# Build the Prose Pod Server image.
edo docker build -t proseim/prose-pod-server:latest "${PROSE_POD_SERVER_DIR:?}"
