#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)/.."}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

test-env-vars 'tutorials/run-locally.md' \
	PROSE_POD_SYSTEM_DIR

export SERVER_ROOT="${PROSE_POD_SYSTEM_DIR:?}"/server/pod
export DATABASE_PATH="${PROSE_POD_SYSTEM_DIR:?}"/local-run.sqlite

edo "${PROSE_POD_SYSTEM_DIR:?}"/tools/cleanup
