#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)/.."}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

test-env-vars 'tutorials/run-locally.md' \
	PROSE_POD_SERVER_DIR \
	PROSE_POD_API_DIR \
	PROSE_POD_SYSTEM_DIR

info 'Updating prose-pod-server…'
edo git -C "${PROSE_POD_SERVER_DIR:?}" pull || :
edo git -C "${PROSE_POD_SERVER_DIR:?}" submodule update

info 'Updating prose-pod-api…'
edo git -C "${PROSE_POD_API_DIR:?}" pull || :
edo git -C "${PROSE_POD_API_DIR:?}" submodule update

info 'Updating prose-pod-system…'
edo git -C "${PROSE_POD_SYSTEM_DIR:?}" pull || :

traced "${SCRIPTS_ROOT:?}"/run-locally/build-images
