openapi: 3.1.0

info:
  title: prose-pod-api
  description: Prose Pod API server.
  contact:
    name: Valerian Saliou
    email: valerian@valeriansaliou.name
  license:
    name: MPL-2.0
    url: https://github.com/prose-im/prose-pod-api/blob/master/LICENSE.md
  version: 0.3.1

servers:
  - url: http://127.0.0.1:8080
    description: Localhost

paths:
  # ===== Init =====
  "/v1/init/first-account":
    put: { $ref: "features/init.yaml#/paths/init_first_account" }
    head: { $ref: "features/init.yaml#/paths/is_first_account_created" }
  "/v1/onboarding-steps":
    get: { $ref: "features/onboarding.yaml#/paths/get_onboarding_steps_statuses" }

  # ===== Auth =====
  "/v1/login":
    post: { $ref: "features/auth.yaml#/paths/login" }
  "/v1/members/{memberId}/password":
    delete: { $ref: "features/auth.yaml#/paths/request_password_reset" }
  "/v1/password-reset-tokens/{token}/use":
    put: { $ref: "features/auth.yaml#/paths/reset_password" }

  # ===== Server config =====
  "/v1/server/config":
    get: { $ref: "features/server-config.yaml#/paths/get_server_config" }
  # === File upload ===
  "/v1/server/config/files":
    delete: { $ref: "features/server-config.yaml#/paths/reset_files_config" }
  "/v1/server/config/file-upload-allowed":
    put: { $ref: "features/server-config.yaml#/paths/set_file_upload_allowed" }
    get: { $ref: "features/server-config.yaml#/paths/get_file_upload_allowed" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_file_upload_allowed" }
  # "/v1/server/config/file-storage-encryption-scheme":
  #   put: { $ref: "features/server-config.yaml#/paths/set_file_storage_encryption_scheme" }
  "/v1/server/config/file-storage-retention":
    put: { $ref: "features/server-config.yaml#/paths/set_file_storage_retention" }
    get: { $ref: "features/server-config.yaml#/paths/get_file_storage_retention" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_file_storage_retention" }
  # === Message archive ===
  "/v1/server/config/messaging":
    delete: { $ref: "features/server-config.yaml#/paths/reset_messaging_config" }
  "/v1/server/config/message-archive-enabled":
    put: { $ref: "features/server-config.yaml#/paths/set_message_archive_enabled" }
    get: { $ref: "features/server-config.yaml#/paths/get_message_archive_enabled" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_message_archive_enabled" }
  "/v1/server/config/message-archive-retention":
    put: { $ref: "features/server-config.yaml#/paths/set_message_archive_retention" }
    get: { $ref: "features/server-config.yaml#/paths/get_message_archive_retention" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_message_archive_retention" }
  # === Push notifications ===
  "/v1/server/config/push-notifications":
    delete: { $ref: "features/server-config.yaml#/paths/reset_push_notifications_config" }
  "/v1/server/config/push-notification-with-body":
    put: { $ref: "features/server-config.yaml#/paths/set_push_notification_with_body" }
    get: { $ref: "features/server-config.yaml#/paths/get_push_notification_with_body" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_push_notification_with_body" }
  "/v1/server/config/push-notification-with-sender":
    put: { $ref: "features/server-config.yaml#/paths/set_push_notification_with_sender" }
    get: { $ref: "features/server-config.yaml#/paths/get_push_notification_with_sender" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_push_notification_with_sender" }
  # === Network encryption ===
  "/v1/server/config/network-encryption":
    delete: { $ref: "features/server-config.yaml#/paths/reset_network_encryption_config" }
  "/v1/server/config/tls-profile":
    put: { $ref: "features/server-config.yaml#/paths/set_tls_profile" }
    get: { $ref: "features/server-config.yaml#/paths/get_tls_profile" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_tls_profile" }
  # === Server federation ===
  "/v1/server/config/server-federation":
    delete: { $ref: "features/server-config.yaml#/paths/reset_server_federation_config" }
  "/v1/server/config/federation-enabled":
    put: { $ref: "features/server-config.yaml#/paths/set_federation_enabled" }
    get: { $ref: "features/server-config.yaml#/paths/get_federation_enabled" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_federation_enabled" }
  "/v1/server/config/federation-whitelist-enabled":
    put: { $ref: "features/server-config.yaml#/paths/set_federation_whitelist_enabled" }
    get: { $ref: "features/server-config.yaml#/paths/get_federation_whitelist_enabled" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_federation_whitelist_enabled" }
  "/v1/server/config/federation-friendly-servers":
    put: { $ref: "features/server-config.yaml#/paths/set_federation_friendly_servers" }
    get: { $ref: "features/server-config.yaml#/paths/get_federation_friendly_servers" }
    delete: { $ref: "features/server-config.yaml#/paths/reset_federation_friendly_servers" }

  # ===== Pod config =====
  "/v1/pod/config":
    get: { $ref: "features/pod-config.yaml#/paths/get_pod_config" }
  "/v1/pod/config/address":
    get: { $ref: "features/pod-config.yaml#/paths/get_pod_address" }
  "/v1/pod/config/dashboard-url":
    get: { $ref: "features/pod-config.yaml#/paths/get_dashboard_url" }

  # ===== Workspace =====
  "/v1/workspace":
    put: { $ref: "features/workspace.yaml#/paths/init_workspace" }
    head: { $ref: "features/workspace.yaml#/paths/is_workspace_initialized" }
    get: { $ref: "features/workspace.yaml#/paths/get_workspace" }
    patch: { $ref: "features/workspace.yaml#/paths/patch_workspace" }
  "/v1/workspace/name":
    put: { $ref: "features/workspace.yaml#/paths/set_workspace_name" }
    get: { $ref: "features/workspace.yaml#/paths/get_workspace_name" }
  "/v1/workspace/accent-color":
    put: { $ref: "features/workspace.yaml#/paths/set_workspace_accent_color" }
    get: { $ref: "features/workspace.yaml#/paths/get_workspace_accent_color" }
  "/v1/workspace/icon":
    put: { $ref: "features/workspace.yaml#/paths/set_workspace_icon" }
    get: { $ref: "features/workspace.yaml#/paths/get_workspace_icon" }

  # ===== Invitations =====
  "/v1/invitations":
    post: { $ref: "features/invitations.yaml#/paths/invite_member" }
    get: { $ref: "features/invitations.yaml#/paths/get_invitations" }
  "/v1/invitations/{invitationId}":
    get: { $ref: "features/invitations.yaml#/paths/get_invitation" }
    delete: { $ref: "features/invitations.yaml#/paths/invitation_cancel" }
  "/v1/invitation-tokens/{token}/details":
    get: { $ref: "features/invitations.yaml#/paths/get_invitation_token_details" }
  "/v1/invitation-tokens/{token}/accept":
    put: { $ref: "features/invitations.yaml#/paths/invitation_accept" }
  "/v1/invitation-tokens/{token}/reject":
    put: { $ref: "features/invitations.yaml#/paths/invitation_reject" }
  "/v1/invitations/{invitationId}/resend":
    post: { $ref: "features/invitations.yaml#/paths/invitation_resend" }

  # ===== Members =====
  "/v1/members":
    get: { $ref: "features/members.yaml#/paths/get_members" }
  "/v1/members/{memberId}":
    get: { $ref: "features/members.yaml#/paths/get_member" }
    delete: { $ref: "features/members.yaml#/paths/delete_member" }
  "/v1/enrich-members":
    get: { $ref: "features/members.yaml#/paths/enrich_members" }
  "/v1/members/{memberId}/role":
    put: { $ref: "features/roles.yaml#/paths/set_member_role" }

  # ===== Network config =====
  "/v1/network/dns/records":
    get: { $ref: "features/dns-setup.yaml#/paths/get_dns_records" }
  "/v1/network/checks":
    get: { $ref: "features/network-checks.yaml#/paths/check_network_configuration" }
  "/v1/network/checks/dns":
    get: { $ref: "features/network-checks-dns.yaml#/paths/check_dns_records" }
  "/v1/network/checks/ip":
    get: { $ref: "features/network-checks-ip.yaml#/paths/check_ip" }
  "/v1/network/checks/ports":
    get: { $ref: "features/network-checks-ports.yaml#/paths/check_ports" }

  # ===== Administration =====
  "/":
    delete: { $ref: "features/factory-reset.yaml#/paths/factory_reset" }
  "/reload":
    post: { $ref: "features/reload.yaml#/paths/reload" }

  # ===== Miscellaneous =====
  "/version":
    get: { $ref: "features/version.yaml#/paths/get_api_version" }
  "/pod/version":
    get: { $ref: "features/version.yaml#/paths/get_pod_version" }

  # ===== Expert =====
  "/v1/server/config/prosody":
    get: { $ref: "features/prosody.yaml#/paths/get_prosody_config" }
  "/v1/server/config/prosody-overrides":
    put: { $ref: "features/prosody.yaml#/paths/set_prosody_overrides" }
    get: { $ref: "features/prosody.yaml#/paths/get_prosody_overrides" }
    delete: { $ref: "features/prosody.yaml#/paths/reset_prosody_overrides" }
  "/v1/server/config/prosody-overrides-raw":
    put: { $ref: "features/prosody.yaml#/paths/set_prosody_overrides_raw" }
    get: { $ref: "features/prosody.yaml#/paths/get_prosody_overrides_raw" }
    delete: { $ref: "features/prosody.yaml#/paths/reset_prosody_overrides_raw" }

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: Basic
    BearerAuth:
      type: http
      scheme: Bearer
