# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/src/service/src/features/app_config/mod.rs

# NOTE: Some configuration keys have been defined via `local-run.env`, so it
#   persists across factory resets.

[branding]
company_name = "Prose (local)"

[server]
domain = "prose.org.local"

[notify.email]
pod_address = "pod@prose.org.local"

smtp_host = "mailpit"
smtp_encrypt = false

[debug_only.dependency_modes]
# notifier = "logging"
