# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/src/service/src/features/app_config/mod.rs

[branding]
company_name = "Prose"

[server]
domain = "prose-demo.org.local"

[notify.email]
pod_address = "pod@prose-demo.org.local"

smtp_host = "mailpit"
smtp_encrypt = false
