#!/bin/bash

# Configure the script to exit when a command fails.
set -e

# https://www.dicebear.com/playground/
# The avatar style <a href="/styles/open-peeps/">Open Peeps</a> is a remix of: <a href="https://www.openpeeps.com/" target="_blank" rel="noopener noreferrer">Open Peeps</a> by <a href="https://twitter.com/pablostanley" target="_blank" rel="noopener noreferrer">Pablo Stanley</a>, licensed under <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener noreferrer">CC0 1.0</a>.

# `npm install --global dicebear` / `volta install dicebear`

# ----------------------------------------------------------------
# Open Peeps by Pablo Stanley
#
# Homepage: https://twitter.com/pablostanley
# Source: https://www.openpeeps.com/
# License: CC0 1.0 - https://creativecommons.org/publicdomain/zero/1.0/
# ----------------------------------------------------------------

DIR="$(date +%s)" && mkdir "$DIR" && dicebear openPeeps "./$DIR" --format png --size 128 --count 32 \
	--accessories 'glasses' 'glasses2' 'glasses3' 'glasses4' 'glasses5' 'sunglasses' 'sunglasses2' \
	--face 'blank' 'calm' 'cheeky' 'contempt' 'cute' 'driven' 'explaining' 'old' 'smile' \
	--head 'afro' 'bangs' 'bangs2' 'bantuKnots' 'bun' 'bun2' 'buns' 'cornrows' 'cornrows2' 'dreads1' 'dreads2' 'flatTop' 'flatTopLong' 'grayBun' 'grayMedium' 'grayShort' 'hatBeanie' 'hatHip' 'hijab' 'long' 'longAfro' 'longBangs' 'longCurly' 'medium1' 'medium2' 'medium3' 'mediumBangs' 'mediumBangs2' 'mediumBangs3' 'mediumStraight' 'mohawk' 'mohawk2' 'noHair1' 'noHair2' 'noHair3' 'pomp' 'shaved1' 'shaved2' 'shaved3' 'short1' 'short2' 'short3' 'short4' 'short5' 'turban' 'twists' 'twists2' \
	--backgroundColor 'ffdfbf' 'ffd5dc' 'd1d4f9' 'c0aede' 'b6e3f4'
