#!/bin/bash

# Configure the script to exit when a command fails.
set -e

export SCRIPTS_ROOT="$(dirname $0)"/..
source "$(dirname $0)"/util.sh

# ===== HELPER FUNCTIONS =====

description() {
	printf "$(cat <<EOF
${Bold}Uninstalls a Prose Pod from a Raspberry Pi.${Bold_Off}
EOF)\n"
}

usage() {
	cat <<EOF
$(format_title 'Usage:')
  You want to deinitialize the Prose Pod from a Raspberry Pi:
    $(format_command $(basename $0))

$(format_title 'Options:')
  $(format_subtitle 'Miscellaneous options:')
    $(format_flag --help)
      Explains what the command does and how to use it.
EOF
}

help() {
	description
	echo ''
	usage
	exit 0
}

# ===== ARGUMENT PARSING =====

for arg in "$@"; do
	case $arg in
		--help) help ;;
		*) die "Unknown argument: ${arg}\n$(usage)" ;;
	esac
done

# ===== MAIN LOGIC =====

rpi_ssh '# Clean things up
	rm -r '"'${REMOTE_PROSE_POD_SYSTEM_DIR}'"'/database.sqlite 2>/dev/null || :'
