#!/usr/bin/env bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

# ===== CONSTANTS =====

: ${SELF:="$(basename $0)"}

: ${REPOSITORY_ROOT:="${SCRIPTS_ROOT:?}"/..}
VERSION_FILE="${REPOSITORY_ROOT:?}"/VERSION
CHANGELOG_FILE="${REPOSITORY_ROOT:?}"/CHANGELOG.md

VERSION="$(cat "${VERSION_FILE:?}")"

# ===== HELPER FUNCTIONS =====

description() {
	cat <<EOF
${Bold}Prepares changelog entries for the next release.${Bold_Off}

This script is not a replacement for writing changelog entries manually, it’s
only there to speed it up. It won’t work if you have already started writing
unreleased changelog entries.
EOF
}

usage() {
	cat <<EOF
$(format_title 'Usage:')
  $(format_command "${SELF:?}")

$(format_title 'Options:')
  $(format_subtitle 'Miscellaneous options:')
    $(format_flag --help)
      Explains what the command does and how to use it.
EOF
}

help() {
	printf "$(description)\n"
	echo ''
	printf "$(usage)\n"
	exit 0
}

to-tag() {
	echo "v${1:?"Must pass a version number"}"
}

# A simplified `sed` command that works on both macOS and Linux.
replace() {
	local find="${1:?}"
	local replace="${2:?}"
	# Escape newlines.
	replace="${replace//$'\n'/\\n}"
	# Escape separator used for sed.
	local SED_PATTERN='@' SED_PATTERN_ESCAPE='#######'
	find="${find//"${SED_PATTERN}"/"${SED_PATTERN_ESCAPE}"}"
	replace="${replace//"${SED_PATTERN}"/"${SED_PATTERN_ESCAPE}"}"
	local pattern="s@${find}@${replace//$'\n'/\\n}@" file="${3:?}"

	if [[ "$(uname)" == "Darwin" ]]; then
		edo sed -i '' -E "$pattern" "$file"
		# Unescape separator used for sed.
		edo sed -i '' -E "s/${SED_PATTERN_ESCAPE}/${SED_PATTERN}/g" "$file"
	else
		edo sed -i "$pattern" "$file"
		# Unescape separator used for sed.
		edo sed -i "s/${SED_PATTERN_ESCAPE}/${SED_PATTERN}/g" "$file"
	fi
}

git-log() {
	git --no-pager log --reverse --no-merges \
		--format="${1:?"Format expected"}" --date=short --color \
		"$(to-tag "${VERSION:?}")"..HEAD
}

# ===== ARGUMENT PARSING =====

for arg in "$@"; do
	case $arg in
		--help) help ;;
		*) error "Unknown argument: $(format_code $arg)."; info "$(usage)"; die ;;
	esac
done

# ===== MAIN LOGIC =====

if ! grep -zq '...HEAD\n\n## \['"${VERSION:?}"'\]' "${CHANGELOG_FILE:?}"; then
	error "Cannot prepare changelog entries when some already exist."
	info "For your information, commits since last release ($(format_code "$(to-tag "${VERSION:?}")")) are:"
	git-log '- %s (in `%C(auto)%h`)'
	die
fi

replace "## \[${VERSION:?}\]" "$(git-log '- %s (in `%h`)')

### Removed

- TODO

### Changed

- TODO

### Added

- TODO

### Fixed

- TODO

## [${VERSION:?}]" "${CHANGELOG_FILE:?}"

success Successfully prepared next changelog entries.

warn '========================================================================'
warn "As stated in $(format_hyperlink 'Keep a Changelog' 'https://keepachangelog.com/en/1.1.0/'), changelogs are meant for humans. This"
warn 'script simplified your job of writing it by inserting all commits since'
warn "last release ($(format_code "$(to-tag "${VERSION:?}")")) but you still have to split it into Removed/"
warn 'Changed/Added/Fixed and make it human-readable. Some commits should'
warn 'probably be removed, and others might need to be squashed into a single'
warn 'changelog entry.'
warn '========================================================================'
