#!/bin/bash

: ${SCRIPTS_ROOT:="$(dirname $0)"}
: ${BASH_TOOLBOX:="${SCRIPTS_ROOT:?}/bash-toolbox"}
# NOTE: `log.sh` provides utility for logging at different levels.
source "${BASH_TOOLBOX:?}"/log.sh

URL='http://127.0.0.1:8000/api-docs/redoc'
if command -v xdg-open &>/dev/null; then
    xdg-open "$URL" &
elif command -v open &>/dev/null; then
    open "$URL" &
else
    die "Neither $(format_code xdg-open) nor $(format_code open) command found. Cannot open URL."
fi

warn "Because the Prose Pod API cannot be started alone, this script uses the local $(format_code proseim/prose-pod-api:latest) image. This means the OpenAPI description will not reload until you run $(format_code 'task build-image -- --debug') again."

ENV_FILE="${PROSE_POD_API_DIR:?}"/crates/api/tests/integration/in-memory.env \
	SERVER_ROOT="${PROSE_POD_SYSTEM_DIR:?}"/server/pod \
	docker compose -f "${PROSE_POD_SYSTEM_DIR:?}"/compose.yaml up
