#!/usr/bin/env bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh
source "${SCRIPTS_ROOT:?}"/constants.sh

PROSE_POD_SERVER_IMAGE_TAG="${LOCAL_DOCKER_TAG:?}"
source "${SCRIPTS_ROOT:?}"/image-names.sh

test-env-vars 'tutorials/run-locally.md' \
	PROSE_POD_API_DIR

# Build the Prose Pod API image.
edo task build-image -- --profile=dev --locked

if [ -n "${PROSE_POD_SERVER_DIR}" ] && [ -d "${PROSE_POD_SERVER_DIR:?}" ]; then
	# Build the Prose Pod Server image.
	edo docker build -t "${PROSE_POD_SERVER_IMAGE:?}" "${PROSE_POD_SERVER_DIR:?}"
fi
