#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

# ===== CONSTANTS =====

LOCAL_RUN_DIR="${PROSE_POD_API_DIR:?}"/local-run
SELF_SCRIPTS="${LOCAL_RUN_DIR:?}"/scripts
source "${SELF_SCRIPTS:?}"/constants.sh

# WIP

# ===== MAIN LOGIC =====

export PROSE_POD_API_IMAGE PROSE_POD_SERVER_IMAGE
export DATABASE_PATH ETC_PROSODY_DIR VAR_LIB_PROSODY_DIR

if [ $# == 0 ]; then
	edo docker compose -f "${COMPOSE_FILE:?}" logs
else
	edo docker compose -f "${COMPOSE_FILE:?}" logs "$@"
fi
