#!/usr/bin/env bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

# ===== CONSTANTS =====

LOCAL_RUN_DIR="${REPOSITORY_ROOT:?}"/local-run
SELF_SCRIPTS="${LOCAL_RUN_DIR:?}"/scripts
source "${SELF_SCRIPTS:?}"/constants.sh

# ===== ARGUMENT PARSING =====

# WIP

# ===== MAIN LOGIC =====

source "${SELF_SCRIPTS:?}"/scenario-files.sh
source "${SELF_SCRIPTS:?}"/scenario-files-fallback.sh
source "${SCENARIO_CONSTANTS_FILE:?}"
source "${SELF_SCRIPTS:?}"/compose-exports.sh

case $# in
	0) edo docker compose -f "${COMPOSE_FILE:?}" logs ;;
	1) edo docker compose -f "${COMPOSE_FILE:?}" logs "$@" --no-log-prefix ;;
	*) edo docker compose -f "${COMPOSE_FILE:?}" logs "$@" ;;
esac
