#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

# ===== CONSTANTS =====

SCENARIO_NAME='demo'

DOMAIN='prose-demo.org.local'
WORKSPACE_NAME='Prose (demo)'
PASSWORD='demo'

MEMBER_ROLES=()
MEMBER_SEXTYPES=()
MEMBER_FIRSTNAMES=()
MEMBER_LASTNAMES=()
MEMBER_DISPLAYNAMES=()
MEMBER_USERNAMES=()
MEMBER_JIDS=()
MEMBER_EMAILS=()
MEMBER_PASSWORDS=()

jid() {
	echo "${1:?}@${DOMAIN:?}"
}

add-member() {
	MEMBER_ROLES+=("${1:?}")
	MEMBER_SEXTYPES+=("${2:?}")
	MEMBER_FIRSTNAMES+=("${3:?}")
	MEMBER_LASTNAMES+=("${4:?}")
	MEMBER_DISPLAYNAMES+=("${5:?}")
	local username="${6:?}"
	MEMBER_USERNAMES+=("${username:?}")
	local jid="$(jid "${username:?}")"
	MEMBER_JIDS+=("${jid:?}")
	MEMBER_EMAILS+=("${7:?}")
	# NOTE: Default password is the user’s JID (thanks to `debug_only.insecure_password_on_auto_accept_invitation = true`).
	MEMBER_PASSWORDS+=("${8:-"${jid:?}"}")
}

# NOTE: https://faker-playground.vercel.app
add-member ADMIN female Pauline Collins 'Pauline C.' 'pauline.collins' 'pauline.collins@example.org' "${PASSWORD:?}"
add-member MEMBER male Todd Schultz 'Todd S.' 'todd.schultz' 'todd.schultz@example.net'
add-member MEMBER female Sheri Nienow 'Sheri N.' 'sheri.nienow' 'sheri.nienow@example.net'
add-member MEMBER male Evan Turner 'Evan T.' 'evan.turner' 'evan.turner@example.com'

# ===== MAIN LOGIC =====

# Create demo scenario.
if [ -d "${PROSE_POD_API_DIR:?}"/local-run/scenarios/"${SCENARIO_NAME:?}" ]; then
	edo task local:scenarios:reset -y -- "${SCENARIO_NAME:?}"
else
	edo task local:scenarios:create -- "${SCENARIO_NAME:?}"
fi

# Run the API.
# NOTE: We need to run `local` so we can auto-accept invitations.
edo task local:run -- --api=local --scenario=demo --detach --no-update
while ! xh :8080/version --check-status -q; do
  sleep 1
done

info 'Initialize XMPP server'
xh PUT :8080/v1/server/config \
	domain="${DOMAIN:?}" \
	--check-status -q

info 'Create first admin account'
xh PUT :8080/v1/init/first-account \
	username="${MEMBER_USERNAMES[0]}" \
	password="${MEMBER_PASSWORDS[0]}" \
	nickname="${MEMBER_DISPLAYNAMES[0]}" \
	--check-status -q

info 'Initialize workspace'
xh PUT :8080/v1/workspace \
	name="${WORKSPACE_NAME:?}" \
	--check-status -q

info 'Log first admin in'
ADMIN_TOKEN="$(xh POST :8080/v1/login -a "${MEMBER_JIDS[0]}:${MEMBER_PASSWORDS[0]}" --check-status -b | jq -r '.token')"

add-member-n() {
	local n="${1:?}"
	info "Add member “${MEMBER_DISPLAYNAMES[n]}” (via auto-accepted invitation)"
	xh POST :8080/v1/invitations \
		auto_accept==true \
		username="${MEMBER_USERNAMES[n]}" \
		pre_assigned_role="${MEMBER_ROLES[n]}" \
		channel=email \
		email_address="${MEMBER_EMAILS[n]}" \
		-A bearer -a "${ADMIN_TOKEN:?}" \
		--check-status -q
}

for n in $(seq 1 $(( ${#MEMBER_USERNAMES[@]} - 1 ))); do
	add-member-n "${n:?}"
done

success 'Done'

edo task local:stop
