#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

LOCAL_RUN_DIR="${PROSE_POD_API_DIR:?}"/local-run
SELF_SCRIPTS="${LOCAL_RUN_DIR:?}"/scripts
source "${SELF_SCRIPTS:?}"/constants.sh

export PROSE_POD_API_IMAGE PROSE_POD_SERVER_IMAGE
export DATABASE_PATH ETC_PROSODY_DIR VAR_LIB_PROSODY_DIR

edo docker compose -f "${COMPOSE_FILE:?}" stop
