#!/bin/bash

# Configure the script to exit when a command fails.
set -e

: ${SCRIPTS_ROOT:="$(dirname $0)"/../../scripts}
export SCRIPTS_ROOT
source "${SCRIPTS_ROOT:?}"/util.sh

LOCAL_RUN_DIR="${PROSE_POD_API_DIR:?}"/local-run
SELF_SCRIPTS="${LOCAL_RUN_DIR:?}"/scripts
edo source "${SELF_SCRIPTS:?}"/constants.sh

edo source "${SELF_SCRIPTS:?}"/scenario-files.sh
edo source "${SELF_SCRIPTS:?}"/compose-exports.sh

edo docker compose -f "${COMPOSE_FILE:?}" stop

if [ -f "${EPHEMERAL_SCENARIO_NAME_FILE:?}" ]; then
	SCENARIO_NAME="$(cat "${EPHEMERAL_SCENARIO_NAME_FILE:?}")"
	if [[ -n "${SCENARIO_NAME-}" ]]; then
		log_as_trace_ task local:scenarios:delete -y -- "${SCENARIO_NAME:?}"
		edo rm "${EPHEMERAL_SCENARIO_NAME_FILE:?}"
	fi
fi
