[package]
name = "prosodyctl"
version = "0.1.0"
edition = "2021"
description = "Rust wrapper around `prosodyctl`."
readme = "README.md"
license = "MPL-2.0"
publish = false
authors = ["Rémi Bardon <remi@remibardon.name>"]

[dependencies]
