# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-system/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/src/service/src/features/app_config/mod.rs

[prosody]
default_storage = "internal"
storage = { roster = "internal" }

[prosody_ext]
additional_modules_enabled = ["storage_internal"]

[branding]
company_name = "Prose (demo)"

[notify.email]
pod_address = "prose@example.org"
smtp_host = "mailpit"
smtp_encrypt = false

[debug_only]
insecure_password_on_auto_accept_invitation = true
