// prose-pod-api
//
// Copyright: 2025, Rémi Bardon <remi@remibardon.name>
// License: Mozilla Public License v2.0 (MPL v2.0)

use prosody_config::*;

use super::ProsodyConfig;

pub fn global_settings() -> prosody_config::ProsodySettings {
    prosody_config::ProsodySettings {
        pidfile: Some("/var/run/prosody/prosody.pid".into()),
        authentication: Some(AuthenticationProvider::InternalHashed),
        default_storage: Some(StorageBackend::Internal),
        log: Some(LogConfig::Map(
            vec![(LogLevel::Debug, LogLevelValue::Console)]
                .into_iter()
                .collect(),
        )),
        http_ports: Some(
            vec![crate::app_config::pub_defaults::SERVER_HTTP_PORT]
                .into_iter()
                .collect(),
        ),
        plugin_paths: Some(
            vec!["/usr/local/lib/prosody/modules"]
                .into_iter()
                .map(ToString::to_string)
                .collect(),
        ),
        modules_enabled: Some(
            vec!["auto_activate_hosts"]
                .into_iter()
                .map(ToString::to_string)
                .collect(),
        ),
        // Disable in-band registrations (done through the Prose Pod Dashboard/API)
        allow_registration: Some(false),
        // consider_websocket_secure: Some(true),
        ..Default::default()
    }
}

pub fn prosody_bootstrap_config() -> ProsodyConfig {
    let config = prosody_config::ProsodyConfig {
        global_settings: global_settings(),
        additional_sections: vec![],
    };

    ProsodyConfig(config)
}

impl ProsodyConfig {
    pub fn print_with_bootstrap_header(&self) -> ProsodyConfigFile {
        self.0.clone().print(vec![
            "Prose Pod Server bootstrap configuration".into(),
            "XMPP Server Configuration".into(),
            r#"/!\ This file has been automatically generated by the Prose Pod API."#.into(),
            r#"/!\ Do NOT edit this file manually or your changes will be overridden during the next reload."#.into(),
        ].into())
    }
}
